version: '3.9'

services:
  postgresdb:
        container_name: postgresdb
        image: postgres:latest
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=shareholders_db
            - TZ=Africa/Kampala
  shareholder-management-service:
        container_name: shareholder-management-service
        image: shareholder-management-service:1.0.0
        environment:
            - SERVER_PORT=8080
            - PROFILE=pre-prod
            - DB_USER=postgres
            - DB_PASS=admin
            - DB_MAX_CONN=5
            - DB_URL=jdbc:postgresql://postgresdb:5432/shareholders_db
            - LOAD_TEST_DATA=true
            - TEST_RECORD_COUNT=25
        ports:
            - "8080:8080"
        depends_on:
            - postgresdb
  shareholders-ui:
    container_name: shareholders-ui
    build: ./
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
            - shareholder-management-service  
networks:
    default:
        name: shareholders-app-net